version: '3.4'

services:
    gost-db:
        image: 127.0.0.1:5001/gostdb-local
        build: ./gostdb-local/
        volumes:
            - /mnt/glusterfs/dtz/gost/postgresql/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - gost-network
        deploy:
            placement:
                constraints:
                    - node.role==worker
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

    gost:
        # environment variables not working in 0.5
        # image: geodan/gost:0.5
        image: geodan/gost
        depends_on:
            - gost-db
        environment:
            GOST_DB_HOST: gost-db
            GOST_SERVER_EXTERNAL_URI: http://192.168.48.71:8082
            GOST_SERVER_MAX_ENTITIES: 200
            GOST_MQTT_ENABLED: "false"
        networks:
            - gost-network
        deploy:
            placement:
                constraints:
                    - node.role==worker
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

    dashboard:
        image: geodan/gost-dashboard
        ports:
          - "8082:8080"
        depends_on:
            - gost
        networks:
            - gost-network
        deploy:
            placement:
                constraints:
                    - node.role==worker
            resources:
                limits:
                    cpus: "1"
                    memory: 4G
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure

networks:
    gost-network:
